name: CapstoneExploration
channels:
  - conda-forge
dependencies:
  - python=3.9
  - flask=2.0
  - pandas=1.4
  - matplotlib=3.5
  - plotly=5.5
  - gdal=3.4
  - libgdal=3.4
  - xarray=0.21
  - jupyter=1.0
  - netcdf4=1.5
  - rioxarray=0.9
  - geopy=2.2
  - requests=2.27
  - numba=0.55
